
version: v1.95.6

landscapeName: gardener-installation

apiserverDomainPrefix: api
wildcardSecretName: gardener-wildcard-tls

identity:
  replicas: 1

gardener:
  shootDomainPrefix: shoot
  seedCandidateDeterminationStrategy: SameRegion

  featureGates: {}

  soil:
    shootDefaultNetworks:
      pods: 100.96.0.0/11
      services: 100.64.0.0/13
    blockCIDRs:
    - 169.254.169.254/32

    gardenlet:
      logging:
        enabled: true
        shootNodeLogging:
          shootPurposes:
          - "infrastructure"
          - "production"
          - "development"
      featureGates:
        HVPA: true
        APIServerSNI: true

    settings:
      excessCapacityReservation:
        enabled: true # this seed will deploy excess-capacity-reservation pods
      scheduling:
        visible: true # the gardener-scheduler will consider this seed for shoots
      shootDNS:
        enabled: true # all shoots on this seed will use DNS, if disabled they'll just use the plain IPs/hostnames
    # loadBalancerServices:
    #   annotations:
    #     foo: bar
      verticalPodAutoscaler:
        enabled: true # a Gardener-managed VPA deployment is enabled
      # deprecated
      ownerChecks:
        enabled: false
