# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- $global := . }}
{{- if .Values.additionalSecrets }}
{{- range .Values.additionalSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ $global.Release.Namespace }}
  labels:
    app: identity
    chart: "{{ $global.Chart.Name }}-{{ $global.Chart.Version }}"
    release: "{{ $global.Release.Name }}"
    heritage: "{{ $global.Release.Service }}"
type: {{ .type | default "Opaque" }}
data:
{{ .data | toYaml | indent 2 }}
{{- end }}
{{- end }}