# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  name: identity-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: identity
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- $hostname := regexReplaceAll "https://([^/]*).*" $.Values.issuerUrl "${1}" }}
{{- $pathname := regexReplaceAll "https://[^/]*(?:/(.+))?" $.Values.issuerUrl "/${1}" }}
spec:
  tls:
    - secretName: {{ .Values.tlsSecretName | default "identity-tls" }}
      hosts:
        - {{ $hostname }}
{{- range .Values.additionalHosts  }}
{{- if not .tlsSecret }}
        - {{ .host }}
{{- end }}
{{- end }}
{{- range .Values.additionalHosts  }}
{{- if .tlsSecret }}
    - secretName: {{ .tlsSecretName }}
      hosts:
        - {{ .host }}
{{- end }}
{{- end }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
        - path: "{{ $pathname }}"
          pathType: "Prefix"
          backend:
            service:
              name: identity-service
              port:
                number: {{ $.Values.servicePort }}
{{- range .Values.additionalHosts  }}
    - host: {{ .host }}
      http:
        paths:
        - path: "{{ $pathname }}"
          pathType: "Prefix"
          backend:
            service:
              name: identity-service
              port:
                number: {{ $.Values.servicePort }}
{{- end }}
