{{ $global := . }}
{{- range .Values.namespaces }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gardener-default
  namespace: {{ . }}
spec:
  # Secret names are always required.
  secretName: {{ $global.Values.secretName }}

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  commonName: {{ $global.Values.commonDnsName }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames: {{ $global.Values.dnsNames | toJson }}
  
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-live
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer

{{- end }}
