{{ $global := . }}
{{- range .Values.secretNamespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-default
  namespace: {{ . }}
type: Opaque
data: {{ required "Provider credentials required" $global.Values.providerCredentials | toJson }}
{{- end }}