---
{{- if .Values.configuration.persistentCache }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "external-dns-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "external-dns-management.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if not (eq .Values.gardener.seed.provider "alicloud") }}
      storage: {{ .Values.configuration.persistentCacheStorageSize }}
      {{- else }}
      storage: {{ .Values.configuration.persistentCacheStorageSizeAlicloud }}
      {{- end }}
{{- end }}
